services:
  - type: web
    name: job-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: postgres://your_neon_user:your_neon_password@your_neon_host/dbname
      - key: SECRET_KEY
        value: your-secret-key
      - key: ENV
        value: production
    autoDeploy: true
